export interface Customers {
    customer_id: string,
    f_degree:string,
    first_name:string,
    last_name:string,
    b_degree:string,
    sex:string,
    born_place:string,
    born_date:string,
    phone_number:number,
    address:string,
    username:string,
    password:string,
    created_at:string,
    updated_at:string,
    created_by:string,
    updated_by:string,
    deleted_by:string,
    email:string,
    institution_id:number,
    deleted_at:string,
    remember_token:string,
    profile_picture:string,
    profession:string,
    education:string,
    born_custom:string
}