export interface Peoples {
    people_id: string,
    front_degree:string,
    first_name:string,
    last_name:string,
    back_degree:string,
    gender:string,
    birth_date:string,
    born_at:string,
    religion:string,
    country_code:string,
    register_with:string,
    username:string,
    password:string,
    phone_number:string,
    profile_picture:string,
    email:string,
    remember_token:string,
    register_id:string,
    address:number,
    point:string,
    is_activated:string,
    social_account:string
}